# Generated by Django 3.1.7 on 2021-03-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210324_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='stripe_cutomer_id',
            new_name='stripe_customer_id',
        ),
    ]
