# Generated by Django 3.1.7 on 2021-03-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210324_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_seller_TOS_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
