# Generated by Django 3.1.7 on 2021-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_stripeconnectsetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeconnectsetup',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
