# Generated by Django 3.1.7 on 2021-03-29 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210328_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconnectsetup',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeconnectsetup',
            name='accept_TOS',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
