# Generated by Django 3.1.7 on 2021-03-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210329_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconnectsetup',
            name='additional_ID',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='stripeconnectsetup',
            name='identity_document_back',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='stripeconnectsetup',
            name='identity_document_front',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
