# Generated by Django 3.1.7 on 2021-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210330_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconnectsetup',
            name='payout_account_number',
            field=models.CharField(default='00000000', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeconnectsetup',
            name='payout_sort_code',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
    ]
