# Generated by Django 3.1.7 on 2021-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210403_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCardSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holders_fullname', models.CharField(max_length=80)),
                ('card_number', models.CharField(max_length=16)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
            ],
        ),
    ]
