# Generated by Django 3.1.7 on 2021-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_addcardsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcardsetup',
            name='cvc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
