# Generated by Django 3.1.7 on 2021-04-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_deliveryaddresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryAddresses',
            new_name='AddDeliveryAddress',
        ),
    ]
