# Generated by Django 3.1.7 on 2021-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210416_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='brand',
            field=models.CharField(default='visa', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='last_4',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
