# Generated by Django 3.1.7 on 2021-04-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210407_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
