# Generated by Django 3.1.7 on 2021-04-27 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
