# Generated by Django 3.1.7 on 2021-05-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
